name=ESP32_BoardCfg
version=0.1.0
author=Gary Thomas <gary@mlbassoc.com>
maintainer=Gary Thomas <gary@mlbassoc.com>
sentence=ESP32 Board Configuration Library
paragraph=ESP32 Board Configuration Library
category=Utility
url=https://github.com/gthomas/ESP32_BoardCfg
includes=BoardCfg.h
architectures=esp32
